project:
  type: website

website:
  title: "Poonam Brar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: about.qmd
        text: About


format:
  html:
    theme:
      - cosmos
      - brand
    css: styles.css
    toc: true



